name: CI/CD - Security Checks and Reporting

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  security_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Bandit Security Scan
        run: |
          pip install bandit
          bandit -r . -f txt -o bandit_report.txt

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: bandit-report
          path: bandit_report.txt

      - name: Safety Check and Report
        run: |
          pip install safety
          safety check --full-report > safety_report.txt || true

      - name: Upload Safety Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: safety-report
          path: safety_report.txt

      - name: Snyk Security Scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=low
        continue-on-error: true
